### ISSUE TITLE
Layer is not used

### ISSUE THREAD

**Issue by plumdog** [aws-samples/parameters-secrets-lambda-extension-sample#1]
Per
- https://github.com/aws-samples/parameters-secrets-lambda-extension-sample/blob/4cf00c01401f184306615d9ca35c3bd33cac4748/template.yaml#L280-L281
- and https://github.com/aws-samples/parameters-secrets-lambda-extension-sample/blob/4cf00c01401f184306615d9ca35c3bd33cac4748/template.yaml#L42-L45

The layer that I think is the reason for this sample to exist isn't actually used in the code.

**Comment by pulp073** [comment]
Greetings, 

This code is part of our [blog](https://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/) and we have included instructions within the blog on how to manually add the lambda extension layer from console to make it easier for users to become familiar with this feature. As a result, the Layers section of the code is commented out. But if you prefer to add layers from code, feel free to uncomment and use it. Thank you for the feedback !
